# Generated by Django 4.1 on 2022-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/images/')),
            ],
        ),
    ]
